"""SQLAlchemy declarative base + shared metadata.

US-E3-02 ships *migrations*, not ORM models — those land in US-E3-04. This module
exists so Alembic has a single `MetaData` target (`Base.metadata`) to point its
`target_metadata` at, and so model modules added tomorrow register against the same
base. A consistent naming convention keeps autogenerated constraint names stable
across migrations.
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Deterministic constraint/index naming so Alembic autogenerate stays stable.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by all ORM models (US-E3-04)."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
